import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster />
        <footer className="fixed bottom-2 right-2 text-xs text-muted-foreground/50 font-mono">
          {process.env.NEXT_PUBLIC_COMMIT_HASH && (
            <p className="text-xs text-muted-foreground">
              {' '}
              <a
                href={`https://github.com/orosound/license-app-web/commit/${process.env.NEXT_PUBLIC_COMMIT_HASH}`}
                target="_blank"
                rel="noopener noreferrer"
                className="hover:underline hover:text-primary"
              >
                {process.env.NEXT_PUBLIC_COMMIT_HASH}
              </a>
            </p>
          )}
        </footer>
      </body>
    </html>
  );
}
